name: intake-dynamodb
channels:
  - intake
  - informaticslab
  - defaults
dependencies:
  - python=3.6
  - intake
  - intake-dynamodb
  - boto3
  - pip:
    - sphinx
    - sphinx-rtd-theme
    - numpydoc
